### ISSUE TITLE
Super Meat Boy

### ISSUE THREAD

**Issue by TheMercenary333** [skyline-emu/skyline-games-list#1173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

Edge-6

### Android Version

10

### SoC type

Kirin

### Device GSMArena link

https://www.gsmarena.com/huawei_p_smart_2019-9409.php

### Game Behaviour

- The game is playable
- The game gives about 30 FPS but sometimes it increases and decreases
- Not smooth without 60 FPS

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[Super Meat Boy_h.txt](https://github.com/skyline-emu/skyline-games-list/files/9905419/Super.Meat.Boy_h.txt)

**Comment by K11MCH1** [comment]
I have copied this over to the existing post.
However, since an issue for this game already exists, I will close this.
Only 1 issue per game allowed. If an issue already exists for a game and you need to report an update you need to post it in the comment section.

Kindly use the search tool next time.
